id: I07240379
initial_creation_type: ebook
source_metadata:
  id: RDI-KK-14
  title: དྭགས་བརྒྱུད་སྒྲུབ་པའི་ཐེམ་སྐས་གདམས་ངག་ཕྱོགས་བསྒྲིགས།
  author: མཛད་པ་པོ། ཀརྨ་རང་བྱུང་ཀུན་ཁྱབ།, མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་ཡོན་ཏན་རྒྱ་མཚོ།,
    མཛད་པ་པོ། ཡོངས་དགེ་མི་འགྱུར་རྡོ་རྗེ།, མཛད་པ་པོ། མཁས་གྲུབ་རཱ་ག་ཨ་སྱས།, མཛད་པ་པོ།
    རྒྱལ་བ་རྒོད་ཚང་པ།
  authors: &id001
  - མཛད་པ་པོ། ཀརྨ་རང་བྱུང་ཀུན་ཁྱབ།
  - མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་ཡོན་ཏན་རྒྱ་མཚོ།
  - མཛད་པ་པོ། ཡོངས་དགེ་མི་འགྱུར་རྡོ་རྗེ།
  - མཛད་པ་པོ། མཁས་གྲུབ་རཱ་ག་ཨ་སྱས།
  - མཛད་པ་པོ། རྒྱལ་བ་རྒོད་ཚང་པ།
  sku: RDI-KK-14
  cover: RDI-KK-14.jpeg
  volume: {}
ebook_metadata:
  title: དྭགས་བརྒྱུད་སྒྲུབ་པའི་ཐེམ་སྐས་གདམས་ངག་ཕྱོགས་བསྒྲིགས།
  authors: *id001
  sku: RDI-KK-14
  cover: RDI-KK-14.jpeg
layers:
- Author
- BookNumber
- BookTitle
- Chapter
- Citation
- Commentary
- Footnote
- Sabche
- Tsawa
- Yigchung
